spring.application.name=todo

# Usa la variable de entorno de Render. Si no existe (en local), busca localhost.
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# Forzamos el dialecto para evitar el error "Unable to determine Dialect"
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Mostrar los errores detallados en consola si algo falla
spring.jpa.show-sql=true